/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/tRRnNI7t03H
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardHeader, CardContent, CardFooter } from "@/components/ui/card"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"

export function chatbot() {
  return (
    <Card className="w-full max-w-md mx-auto">
      <CardHeader className="flex items-center justify-between border-b px-4 py-3">
        <div className="flex items-center gap-3">
          <Avatar>
            <AvatarImage src="/chatgpticon.png" alt="Chatbot Avatar" />
          </Avatar>
          <div>
            <p className="text-sm font-medium">Chatbot Assistant</p>
            <p className="text-xs text-muted-foreground">Online</p>
          </div>
        </div>
        <Button size="icon" variant="ghost" className="rounded-full">
          <XIcon className="h-4 w-4" />
          <span className="sr-only">Close chat</span>
        </Button>
      </CardHeader>
      <CardContent className="h-[400px] overflow-y-auto px-4 py-3">
        <div className="space-y-4">
          <div className="flex w-max max-w-[75%] flex-col gap-2 rounded-lg bg-muted px-3 py-2 text-sm">
            <p>Hi there! How can I assist you today?</p>
            <p className="text-xs text-muted-foreground">Chatbot</p>
          </div>
          <div className="flex w-max max-w-[75%] flex-col gap-2 rounded-lg bg-primary text-primary-foreground px-3 py-2 text-sm ml-auto">
            <p>I'm having trouble with my account. Can you help me?</p>
            <p className="text-xs text-primary-foreground/80">You</p>
          </div>
          <div className="flex w-max max-w-[75%] flex-col gap-2 rounded-lg bg-muted px-3 py-2 text-sm">
            <p>Sure, no problem! What seems to be the issue with your account?</p>
            <p className="text-xs text-muted-foreground">Chatbot</p>
          </div>
          <div className="flex w-max max-w-[75%] flex-col gap-2 rounded-lg bg-primary text-primary-foreground px-3 py-2 text-sm ml-auto">
            <p>I'm not able to log in. It keeps saying my credentials are invalid.</p>
            <p className="text-xs text-primary-foreground/80">You</p>
          </div>
          <div className="flex w-max max-w-[75%] flex-col gap-2 rounded-lg bg-muted px-3 py-2 text-sm">
            <p>Okay, let's troubleshoot that. Can you try resetting your password?</p>
            <p className="text-xs text-muted-foreground">Chatbot</p>
          </div>
        </div>
      </CardContent>
      <CardFooter className="border-t px-4 py-3">
        <form className="flex items-center gap-2">
          <Input id="message" placeholder="Type your message..." className="flex-1" autoComplete="off" />
          <Button type="submit" size="icon">
            <SendIcon className="h-4 w-4" />
            <span className="sr-only">Send</span>
          </Button>
        </form>
      </CardFooter>
    </Card>
  )
}

function SendIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m22 2-7 20-4-9-9-4Z" />
      <path d="M22 2 11 13" />
    </svg>
  )
}


function XIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
