/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/loQ09v7HgP4
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Card, CardHeader, CardContent } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"

export function hompagemodal() {
  return (
    <Card className="w-full max-w-md mx-auto p-6">
      <CardHeader className="flex justify-between border-b pb-4">
        <div className="flex items-center space-x-4">
          <Button variant="link" className="text-black font-bold border-b-2 border-red-500">
            Track order
          </Button>
          <Button variant="link" className="text-muted-foreground">
            Ship order
          </Button>
        </div>
      </CardHeader>
      <CardContent className="space-y-6">
        <div className="text-center">
          <h2 className="text-xl font-bold">Track your order through</h2>
        </div>
        <div className="flex justify-between space-x-2">
          <Button variant="outline" className="flex-1">
            Mobile
          </Button>
          <Button variant="outline" className="flex-1">
            AWB
          </Button>
          <Button variant="outline" className="flex-1 bg-black text-white">
            Order Id
          </Button>
          <Button variant="outline" className="flex-1">
            LRN
          </Button>
        </div>
        <div>
          <Input placeholder="Enter your Order Id" className="w-full" />
        </div>
        <div className="text-center">
          <Button className="w-full bg-black text-white">Track Order</Button>
        </div>
        <div className="text-center text-muted-foreground text-sm">
          Live tracking updates & extra support on our App
        </div>
        <div className="flex justify-center space-x-4">
          <Button variant="link" className="flex items-center space-x-2">
            <img
              src="/placeholder.svg"
              alt="Google Play"
              className="h-6 w-6"
              width="24"
              height="24"
              style={{ aspectRatio: "24/24", objectFit: "cover" }}
            />
            <span>Get it on Google Play</span>
          </Button>
          <Button variant="link" className="flex items-center space-x-2">
            <img
              src="/placeholder.svg"
              alt="App Store"
              className="h-6 w-6"
              width="24"
              height="24"
              style={{ aspectRatio: "24/24", objectFit: "cover" }}
            />
            <span>Download on the App Store</span>
          </Button>
        </div>
      </CardContent>
    </Card>
  )
}
